#!/bin/bash
echo "Chek the eval(btn.onclick = function.... in EDIT.JS. btn must be renamed with the new short variable."
#cc=(indexmenu edit nojsindex)
cc=(indexmenu edit)
cc2=(indexmenu)
echo "Compacting ${cc[*]}"
for ((a=0; a<${#cc[@]}; a++)); do
 echo "Compacting ${cc[$a]}"
 jscompact --newlines --infile=${cc[$a]}-full.js --outfile=${cc[$a]}.js.tmp
 for ((c=0; c<${#cc2[@]}; c++)); do
  if [ $c = $a ]; then
   echo "Manage ${cc[$a]} Copyright head"
   head -18 ${cc[$a]}-full.js > ${cc[$a]}.js.tmp2
   cat ${cc[$a]}.js.tmp >> ${cc[$a]}.js.tmp2
   mv ${cc[$a]}.js.tmp2 ${cc[$a]}.js.tmp
  fi;
 done;
 js_compactor --opt --comment_exception=copyright --force --src=${cc[$a]}.js.tmp --dest=${cc[$a]}.js
 rm -f ${cc[$a]}.js.tmp ${cc[$a]}.js.tmp2 
 echo "New ${cc[$a]}.js created!"
done;
